kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /drone
  path: src/github.com/justindfuller/purchase-plan

steps:
  - name: backend-lint
    image: golangci/golangci-lint
    pull: if-not-exists
    commands:
      - cd backend
      - golangci-lint run
    when:
      event: [push, tag]

  - name: backend
    image: nytimes/golang-gcloud-sdk:latest
    pull: if-not-exists
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /drone/service_account_credentials.json
      SERVICE_ACCOUNT_CREDENTIALS:
        from_secret: APP_ENGINE_CREDENTIALS_DEV
    commands:
      - ./scripts/setup
      - cd backend
        # - make test
      - make build
    when:
      event: [push, tag]

  - name: frontend
    image: node:15
    pull: if-not-exists
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - mkdir ../backend/frontend/
      - cp -r ./build/ ../backend/frontend/
    when:
      event: [push, tag]

  - name: setup-terraform
    image: bash
    pull: if-not-exists
    environment:
      SERVICE_ACCOUNT_CREDENTIALS:
        from_secret: TERRAFORM_CREDENTIALS
    commands:
      - ./scripts/setup
    depends_on:
      - backend

  - name: terraform-dev
    image: hashicorp/terraform:light
    pull: if-not-exists
    environment:
        GOOGLE_APPLICATION_CREDENTIALS: /drone/service_account_credentials.json
    commands:
      - cd terraform/dev
      - terraform init
        # - terraform apply -auto-approve
    when:
      event: push
      branch: main
    depends_on:
      - setup-terraform
    
  - name: deploy-dev
    image: nytimes/drone-gae
    pull: if-not-exists
    environment:
      GAE_CREDENTIALS:
        from_secret: DRONE_CREDENTIALS_DEV
    settings:
      action: deploy
      project: purchase-plan-dev
      dir: backend/cmd/server
      app_file: dev.yaml
      max_versions: 10
    when:
      event: push
      branch: main
    depends_on:
      - frontend
      - backend
      - backend-lint
      - terraform-dev

  - name: e2e-dev
    image: cypress/included:6.4.0
    pull: if-not-exists
    commands:
      - cd e2e
      - npm ci
      - npm test -- --config baseUrl=https://dev.purchaseplan.io
    when:
      environment:
        TEST_URL: https://dev.purchaseplan.io
      event: push
      branch: main
    depends_on:
      - deploy-dev

  - name: slack-dev
    image: plugins/slack
    pull: if-not-exists
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: drone-alerts
      link_names: true
      template: >
        {{#success build.status}}
          build {{build.link}} (dev deploy) succeeded.
        {{else}}
          build {{build.link}} (dev deploy) failed.
        {{/success}}
    depends_on:
      - e2e-dev
    when:
      event: push
      branch: [main]
      status: [ success, failure  ]

  - name: terraform-prd
    image: hashicorp/terraform:light
    pull: if-not-exists
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /drone/service_account_credentials.json
    commands:
      - cd terraform/prd
      - terraform init
        # - terraform apply -auto-approve
    when:
      event: [push, tag]
      branch: [main]
    depends_on:
      - e2e-dev
      - setup-terraform

  - name: deploy-prd
    image: nytimes/drone-gae
    pull: if-not-exists
    environment:
      GAE_CREDENTIALS:
        from_secret: DRONE_CREDENTIALS_PRD
    settings:
      action: deploy
      project: purchase-plan-prd
      dir: backend/cmd/server
      app_file: prd.yaml
      max_versions: 10
    when:
      event: [push, tag]
      branch: [main]
    depends_on:
      - frontend
      - backend
      - terraform-prd

  - name: build-android
    image: node:15
    pull: if-not-exists
    environment:
      EXPO_TOKEN:
        from_secret: EXPO_TOKEN
    commands:
      - cd mobile
      - npm i -g expo-cli
      - expo build:android -t app-bundle --no-publish --no-wait
    when:
      event: [push, tag]
      branch: [main]

  ## - name: publish-android
  ##  image: node:15
  ##  pull: if-not-exists
  ##  environment:
  ##    EXPO_TOKEN:
  ##      from_secret: EXPO_TOKEN
  ##  commands:
  ##    - cd mobile
  ##    - npm i -g expo-cli
  ##    - expo login
  ##    - expo upload:android --latest --track=internal
  ##  depends_on:
  ##    - build-android
  ##    - deploy-prd
  ##  when:
  ##    event: [push, tag]
  ##    branch: [main]

  - name: slack-prd
    image: plugins/slack
    pull: if-not-exists
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: drone-alerts
      link_names: true
      template: >
        {{#success build.status}}
          @here build {{build.link}} (production deploy) succeeded.
        {{else}}
          @here build {{build.link}} (production deploy) failed.
        {{/success}}
    depends_on:
      - deploy-prd
      - build-android
    when:
      event: [push, tag]
      branch: [main]
      status: [ success, failure  ]
