runtime: go115
service: default

env_variables:
  PURCHASE_PLAN_IMAGE_BUCKET: "purchase-plan-images-dev"
  ENV: "development"

handlers:
  - url: /static/css
    static_dir: frontend/build/static/css
    secure: always

  - url: /static/js
    static_dir: frontend/build/static/js
    secure: always

  - url: /static/media
    static_dir: frontend/build/static/media
    secure: always

  - url: /static
    static_dir: frontend/build/static
    secure: always

  - url: /v1/.*
    script: auto
    secure: always

  - url: /public
    static_dir: frontend/build
    secure: always

  - url: /app/.*
    static_files: frontend/build/index.html
    upload: frontend/build/index\.html
    secure: always

  - url: /app/legal/privacy-policy
    static_files: frontend/build/privacy-policy.html
    upload: frontend/build/privacy-policy\.html
    secure: always

  - url: /app/legal/terms-of-service
    static_files: frontend/build/terms-of-service.html
    upload: frontend/build/terms-of-service\.html
    secure: always

  - url: /
    static_files: frontend/build/index.html
    upload: frontend/build/index\.html
    secure: always
