runtime: go116
service: default

env_variables:
  PURCHASE_PLAN_IMAGE_BUCKET: "purchase-plan-images-dev"
  ENV: "development"

handlers:
  ## All API requests are prefixed with /v1
  - url: /v1/.*
    script: auto
    secure: always

  ## All Purchase Plan static files begin with /purchase
  - url: /purchase/static/css
    static_dir: purchase/frontend/build/static/css
    secure: always

  - url: /purchase/static/js
    static_dir: purchase/frontend/build/static/js
    secure: always

  - url: /purchase/static/media
    static_dir: purchase/frontend/build/static/media
    secure: always

  - url: /purchase/static
    static_dir: purchase/frontend/build/static
    secure: always
  
  - url: /purchase
    static_dir: purchase/frontend/build
    secure: always

  ## All Purchase Plan Routes begin with /app
  - url: /app/legal/privacy-policy
    static_files: purchase/frontend/build/privacy-policy.html
    upload: purchase/frontend/build/privacy-policy\.html
    secure: always

  - url: /app/legal/terms-of-service
    static_files: purchase/frontend/build/terms-of-service.html
    upload: purchase/frontend/build/terms-of-service\.html
    secure: always

  - url: /app/.*
    static_files: purchase/frontend/build/index.html
    upload: purchase/frontend/build/index\.html
    secure: always

  ## All Budget files begin with /budget
  - url: /budget/static/css
    static_dir: budget/frontend/build/static/css
    secure: always

  - url: /budget/static/js
    static_dir: budget/frontend/build/static/js
    secure: always

  - url: /budget/static/media
    static_dir: budget/frontend/build/static/media
    secure: always

  - url: /budget/static
    static_dir: budget/frontend/build/static
    secure: always

  - url: /budget
    static_files: budget/frontend/build/index.html
    upload: budget/frontend/build/index\.html
    secure: always

    # - url: /budget
    # static_dir: budget/frontend/build
    # secure: always

  - url: /budget/.*
    static_files: budget/frontend/build/index.html
    upload: budget/frontend/build/index\.html
    secure: always
  
  ## Serve purchase plan index.html by default
  - url: /
    static_files: purchase/frontend/build/index.html
    upload: purchase/frontend/build/index\.html
    secure: always
